batch_size: 512 
warm_up: 3 
epochs: 15 

load_model: 3epoch_pretrained_15M 
eval_every_n_epochs: 1 
save_every_n_epochs: 1 
log_every_n_steps: 50 

fp16_precision: False 
init_lr: 0.0005 
weight_decay: 1e-5 
gpu: cuda:0 

model:
  num_layer: 5 
  emb_dim: 300 
  feat_dim: 512 
  drop_ratio: 0 
  pool: mean 

aug: node 
dataset:
  num_workers: 12 
  valid_size: 0.05 
  data_path: # path to the dataset

loss:
  temperature: 0.1 
  use_cosine_similarity: True 
